// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_command.proto

package devicecommandproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSentAt           int64    `protobuf:"varint,4,opt,name=last_sent_at,json=lastSentAt,proto3" json:"last_sent_at,omitempty"`
	Acknowledged         int64    `protobuf:"varint,5,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	TimesSent            int64    `protobuf:"varint,6,opt,name=times_sent,json=timesSent,proto3" json:"times_sent,omitempty"`
	LastStatus           string   `protobuf:"bytes,7,opt,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty"`
	FailureMessage       []byte   `protobuf:"bytes,8,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0e2825df576e403, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Command) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Command) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Command) GetLastSentAt() int64 {
	if m != nil {
		return m.LastSentAt
	}
	return 0
}

func (m *Command) GetAcknowledged() int64 {
	if m != nil {
		return m.Acknowledged
	}
	return 0
}

func (m *Command) GetTimesSent() int64 {
	if m != nil {
		return m.TimesSent
	}
	return 0
}

func (m *Command) GetLastStatus() string {
	if m != nil {
		return m.LastStatus
	}
	return ""
}

func (m *Command) GetFailureMessage() []byte {
	if m != nil {
		return m.FailureMessage
	}
	return nil
}

type DeviceCommand struct {
	DeviceUdid           string     `protobuf:"bytes,1,opt,name=device_udid,json=deviceUdid,proto3" json:"device_udid,omitempty"`
	Commands             []*Command `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	NotNow               []*Command `protobuf:"bytes,5,rep,name=not_now,json=notNow,proto3" json:"not_now,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeviceCommand) Reset()         { *m = DeviceCommand{} }
func (m *DeviceCommand) String() string { return proto.CompactTextString(m) }
func (*DeviceCommand) ProtoMessage()    {}
func (*DeviceCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0e2825df576e403, []int{1}
}

func (m *DeviceCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCommand.Unmarshal(m, b)
}
func (m *DeviceCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCommand.Marshal(b, m, deterministic)
}
func (m *DeviceCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCommand.Merge(m, src)
}
func (m *DeviceCommand) XXX_Size() int {
	return xxx_messageInfo_DeviceCommand.Size(m)
}
func (m *DeviceCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCommand proto.InternalMessageInfo

func (m *DeviceCommand) GetDeviceUdid() string {
	if m != nil {
		return m.DeviceUdid
	}
	return ""
}

func (m *DeviceCommand) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *DeviceCommand) GetNotNow() []*Command {
	if m != nil {
		return m.NotNow
	}
	return nil
}

func init() {
	proto.RegisterType((*Command)(nil), "devicecommandproto.Command")
	proto.RegisterType((*DeviceCommand)(nil), "devicecommandproto.DeviceCommand")
}

func init() { proto.RegisterFile("device_command.proto", fileDescriptor_e0e2825df576e403) }

var fileDescriptor_e0e2825df576e403 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd0, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x70, 0xd2, 0x7f, 0x69, 0xa7, 0x55, 0x61, 0xf0, 0xb0, 0x20, 0xd2, 0xd0, 0x8b, 0x39,
	0xe5, 0xa0, 0x82, 0xe7, 0xa2, 0x57, 0x3d, 0x44, 0x3c, 0x87, 0x35, 0x3b, 0x96, 0x60, 0xb2, 0x5b,
	0xb2, 0x13, 0x83, 0x0f, 0xe0, 0x73, 0xf8, 0xaa, 0x92, 0xdd, 0x6d, 0x41, 0x3c, 0x78, 0x4b, 0x7e,
	0xcc, 0xce, 0xb7, 0xfb, 0xc1, 0xb9, 0xa2, 0x8f, 0xaa, 0xa4, 0xa2, 0x34, 0x4d, 0x23, 0xb5, 0xca,
	0xf6, 0xad, 0x61, 0x83, 0xe8, 0x35, 0xa0, 0xb3, 0xcd, 0xd7, 0x08, 0xe2, 0x7b, 0x0f, 0x88, 0x30,
	0xe9, 0xba, 0x4a, 0x89, 0x28, 0x89, 0xd2, 0x45, 0xee, 0xbe, 0x51, 0x40, 0xbc, 0x97, 0x9f, 0xb5,
	0x91, 0x4a, 0x8c, 0x92, 0x28, 0x5d, 0xe5, 0x87, 0x5f, 0xbc, 0x04, 0x28, 0x5b, 0x92, 0x4c, 0xaa,
	0x90, 0x2c, 0xc6, 0x49, 0x94, 0x8e, 0xf3, 0x45, 0x90, 0x2d, 0x63, 0x02, 0xab, 0x5a, 0x5a, 0x2e,
	0x2c, 0x69, 0x1e, 0x06, 0x26, 0x6e, 0x00, 0x06, 0x7b, 0x26, 0xcd, 0x5b, 0xc6, 0x0d, 0xac, 0x64,
	0xf9, 0xae, 0x4d, 0x5f, 0x93, 0xda, 0x91, 0x12, 0x53, 0x37, 0xf1, 0xcb, 0x86, 0x10, 0xae, 0x1a,
	0xb2, 0x6e, 0x8d, 0x98, 0xf9, 0x10, 0x27, 0xc3, 0x12, 0x5c, 0xc3, 0xd2, 0x87, 0xb0, 0xe4, 0xce,
	0x8a, 0xd8, 0x5d, 0xdc, 0x67, 0x38, 0xc1, 0x2b, 0x38, 0x7b, 0x93, 0x55, 0xdd, 0xb5, 0x54, 0x34,
	0x64, 0xad, 0xdc, 0x91, 0x98, 0xbb, 0x67, 0x9c, 0x06, 0x7e, 0xf4, 0xba, 0xf9, 0x8e, 0xe0, 0xe4,
	0xc1, 0xd5, 0x73, 0x68, 0x63, 0x0d, 0xcb, 0xd0, 0x62, 0xa7, 0x8e, 0xa5, 0x80, 0xa7, 0x17, 0x55,
	0x29, 0xbc, 0x83, 0x79, 0xa8, 0xd2, 0x8a, 0x51, 0x32, 0x4e, 0x97, 0xd7, 0x17, 0xd9, 0xdf, 0x86,
	0xb3, 0xb0, 0x2f, 0x3f, 0x0e, 0xe3, 0x2d, 0xc4, 0xda, 0x70, 0xa1, 0x4d, 0x2f, 0xa6, 0xff, 0x9f,
	0x9b, 0x69, 0xc3, 0x4f, 0xa6, 0x7f, 0x9d, 0x39, 0xbe, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe3,
	0xa5, 0x7a, 0x99, 0xdc, 0x01, 0x00, 0x00,
}
